# Generated by Django 4.1.2 on 2022-10-14 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Linha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('imagem', models.ImageField(upload_to='')),
                ('ingredientes', models.TextField()),
                ('validade', models.TextField()),
                ('ativo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Tabela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('val_ener', models.CharField(max_length=255)),
                ('val_ener_vd', models.CharField(max_length=255)),
                ('val_carbo', models.CharField(max_length=255)),
                ('val_carbo_vd', models.CharField(max_length=255)),
                ('val_prote', models.CharField(max_length=255)),
                ('val_prote_vd', models.CharField(max_length=255)),
                ('val_gtotal', models.CharField(max_length=255)),
                ('val_gtotal_vd', models.CharField(max_length=255)),
                ('val_gsatu', models.CharField(max_length=255)),
                ('val_gsatu_vd', models.CharField(max_length=255)),
                ('val_gtrans', models.CharField(max_length=255)),
                ('val_gtrans_vd', models.CharField(max_length=255)),
                ('val_fibra', models.CharField(max_length=255)),
                ('val_fibra_vd', models.CharField(max_length=255)),
                ('val_sodio', models.CharField(max_length=255)),
                ('val_sodio_vd', models.CharField(max_length=255)),
            ],
        ),
    ]
