# Generated by Django 4.1.2 on 2022-10-14 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_publico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='linha',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='site_publico.linha'),
        ),
        migrations.AddField(
            model_name='produto',
            name='tabela',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='site_publico.tabela'),
        ),
    ]
