# Generated by Django 4.1.2 on 2022-10-14 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_publico', '0002_produto_linha_produto_tabela'),
    ]

    operations = [
        migrations.AddField(
            model_name='linha',
            name='imagem',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
