# Generated by Django 4.1.2 on 2022-10-19 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_publico', '0003_linha_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
